# Generated by Django 3.0.7 on 2021-01-21 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='employee',
            new_name='Student',
        ),
    ]
