# Generated by Django 3.0.7 on 2021-01-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0002_auto_20210121_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='blog_image',
            field=models.ImageField(default='', upload_to='media'),
        ),
    ]
